# Settings
permalink: /:categories/:title

# About
title: AWS
tagline: Applications Web et Sécurité
authors:
  - name: Luca De Feo
    url: 'http://defeo.lu/'
  - name: Sébastien Besnier
  - name: Erik Bray
  - name: Nicolas Gama
    url: 'http://gama.nicolas.free.fr/'
  - name: Valentin Suder
    url: 'http://suder.xyz/'
created: 2013
license:
  name: Creative Commons 4.0 Attribution-ShareAlike
  shortname: CC-BY-SA 4.0
  url: https://creativecommons.org/licenses/by-sa/4.0/
  badge: https://i.creativecommons.org/l/by-sa/4.0/80x15.png

# Display a log in the top bar
#logo: assets/logo/eLeMentS.svg

# Display a GitHub fork me logo in the lower right corner
forkme: yes

# Default configuration for pages.
# Can be used to activate addons on all pages.
defaults:
  - scope:
      path: ''
    values:
      layout: default
      addons:
        favicon: yes
        muut: yes
        clicker:
          host: 'https://clicker-uvsq.herokuapp.com'
          methods: 
            - title: " GitHub"
              icon: github
              path: /login/github
          messages:
            loginError: Veulliez vous connecter pour visualiser ce questionnaire.
            unknownError: "Une erreur s'est produite, veuillez réessayer."
            submitError: "Impossible d'envoyer le questionnaire, veuillez réessayer."
            submit: "Envoyer réponse"
            submitted: "Réponse envoyée"
            deadline: "Vous pouvez modifier votre réponse jusqu'au"
  - scope:
      path: '_lessons'
    values:
      addons:
        slideshow: { width: 1000, height: 562.5 }
        recorder: yes
        style_goodies: yes
  - scope:
      path: '_tutorials'
    values:
      layout: article
      addons:
        style_goodies: yes
  - scope:
      path: defenses
    values:
      layout: null

# New page / post / etc. menu
#create:
#  pages: yes
#  collections:
#    - key: posts
#      template: Write something
#    - key: tutorials
#      template: Write a tutorial

collections:
  addons:
    output: true
    permalink: /:collection/:path:output_ext
  projects:
  lessons: 
    output: true
    name: Leçons
  tutorials:
    name: TDs
    output: true

# Kramdown configuration (markdown parser)
kramdown:
  parse_block_html: true
highlighter: null

# Prose.io configuration, if that's your style
#prose: no

# SASS configuration.
# Better not touch this
sass:
  sass_dir: assets/css
  style: compressed

plugins:
  - jekyll-coffeescript
  
